name: Build and Push Debian 12 Docker Image

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

env:
  IMAGE_NAME: iamenr0s/docker-debian12-ansible

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Extract tag name
        run: echo "X_TAG=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV          
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./debian12/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.X_TAG }}
          platforms: linux/amd64,linux/arm64
