name: Build and Push Fedora 39 Docker Image

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    paths-ignore:
      - '**/*.md'

env:
  IMAGE_NAME: iamenr0s/docker-fedora39-ansible

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}            
      -
        name: Extract tag name
        run: echo "X_TAG=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV          
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./fedora39/Dockerfile
          push: true
          tags: |
            docker.io/${{ env.IMAGE_NAME }}:latest
            docker.io/${{ env.IMAGE_NAME }}:${{ env.X_TAG }}
            quay.io/${{ env.IMAGE_NAME }}:latest
            quay.io/${{ env.IMAGE_NAME }}:${{ env.X_TAG }}            
          platforms: linux/amd64,linux/arm64
