name: Build and Push Docker Image

on:
  push:
    branches:
      - 'main'

env:
  IMAGE_NAME: enros/docker-rockylinux8-ansible

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm/v7, linux/arm64]    
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Get tag
        uses: olegtarasov/get-tag@v2.1.2
        id: tagName
        with:
          tagRegexGroup: 1
      -
         name: Set Tag Variable
         run: |
           echo ::set-env name=TAG::$GIT_TAG_NAME
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./rockylinux8/
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          platforms: ${{ matrix.platform }}
